#!/usr/bin/env bash
echo "Cloning dependencies"
git clone --depth=1 https://github.com/z4nyx/linaro -b arm64/latest-7 gcc
git clone https://github.com/z4nyx/AnyKernel3.git -b lavender --depth=1 AnyKernel
echo "Done"
IMAGE="$(pwd)/out/arch/arm64/boot/Image.gz-dtb"
TANGGAL=$(date +"%H%M-%Y%m%d")
export CROSS_COMPILE=~/gcc/bin/aarch64-linux-gnu-
export ARCH=arm64
export SUBARCH=arm64
export KBUILD_BUILD_USER=z4nyx
export KBUILD_BUILD_HOST=circleci
# Push kernel to channel
function push() {
    cd AnyKernel || exit 1
    ZIP=$(echo *.zip)
    curl -F document=@$ZIP "https://api.telegram.org/bot$token/sendDocument" \
        -F chat_id="$haikal"
}
# Fin Error
function finerr() {
    curl -s -X POST "https://api.telegram.org/bot$token/sendMessage" \
        -d chat_id="$haikal" \
        -d "disable_web_page_preview=true" \
        -d "parse_mode=markdown" \
        -d text="Build throw an error(s)"
    exit 1
}
# Compile plox
function compile() {
    mkdir -p out
    make O=out lavender-perf_defconfig
    make O=out -j$(nproc --all)

    if ! [ -a "$IMAGE" ]; then
        finerr
        exit 1
    fi
    cp out/arch/arm64/boot/Image.gz-dtb AnyKernel
}
# Zipping
function zipping() {
    cd AnyKernel || exit 1
    zip -r9 Amethyst-lavender-${TANGGAL}.zip *
    cd ..
}
compile
zipping
push
