#!/usr/bin/env bash
echo "Cloning dependencies"
git clone --depth=1 -j$(nproc --all) https://github.com/KudProject/aarch64-linux-android-4.9 gcc
git clone --depth=1 -j$(nproc --all) https://github.com/z4nyx/AnyKernel3.git -b lavender AnyKernel
echo "Done"
IMAGE="$(pwd)/out/arch/arm64/boot/Image.gz-dtb"
TANGGAL=$(date +"%Y%m%d%H")
GCC="$(pwd)/gcc/bin/aarch64-linux-android-"
export ARCH=arm64
export SUBARCH=arm64
export KBUILD_BUILD_USER=z4nyx
export KBUILD_BUILD_HOST=circleci
# Push kernel to channel
function push() {
    cd AnyKernel || exit 1
    ZIP=$(echo *.zip)
    curl -F document=@$ZIP "https://api.telegram.org/bot$token/sendDocument" \
        -F chat_id="$haikal"
}
# Fin Error
function finerr() {
    curl -s -X POST "https://api.telegram.org/bot$token/sendMessage" \
        -d chat_id="$haikal" \
        -d "disable_web_page_preview=true" \
        -d "parse_mode=markdown" \
        -d text="Build throw an error(s)"
    exit 1
}
# Compile plox
function compile() {
    make O=out ARCH=arm64 lavender-perf_defconfig
    make -j$(nproc --all) O=out ARCH=arm64 CROSS_COMPILE=${GCC}

    if ! [ -a "$IMAGE" ]; then
        finerr
        exit 1
    fi
    cp out/arch/arm64/boot/Image.gz-dtb AnyKernel
}
# Zipping
function zipping() {
    cd AnyKernel || exit 1
    zip -r9 Amethyst-Kernel-lavender-${TANGGAL}.zip *
    cd ..
}
compile
zipping
push
